name: Email Agent

on:
  schedule:
    # Run at 9 AM, 2 PM, and 7 PM UTC
    - cron: '0 9,14,19 * * *'
  workflow_dispatch: # Allow manual runs

jobs:
  run-email-agent:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create credentials file
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
        
    - name: Create token files
      run: |
        echo '${{ secrets.TOKEN1_JSON }}' > token1.json
        echo '${{ secrets.TOKEN2_JSON }}' > token2.json
        
    - name: Run email agent
      run: |
        python run_graph.py
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: email-agent-results
        path: output_*.json
        retention-days: 7 